services:
  db:
    image: postgres
    container_name: javaTestDB
    ports:
      - '5440:5432'
    restart: always
    environment:
      POSTGRES_DB: javaTestDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ChangeMeInProd!
    volumes:
      - javaTestDB-pg-data:/var/lib/postgresql/18/docker

volumes:
  javaTestDB-pg-data:
